name: Generate HTML and deploy

on:
  push:
    branches:
      - main
      - humble

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all branches
        run: |
          for remote in $(git branch -r | grep -v '\->'); do
            branch=${remote#origin/}
            if [ -z "$(git branch --list $branch)" ]; then
              git branch --track $branch $remote
            else
              echo "Branch $branch already exists, skipping."
            fi
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-tabs sphinx-multiversion sphinx-design
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Sphinx build
        run: |
          sphinx-multiversion source build/html
      - name: Create index.html
        run: |
          cp source/_templates/index.html build/html/ 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/html"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
